title: "Zeynep Guven Tunalioglu"
description: "PhD student in Applied Mathematics"
theme: minima
author: "Zeynep Guven Tunalioglu"
email: "Zeynep.Guven-Tunalioglu@warwick.ac.uk"


url: "https://zeynepguvent.github.io"
baseurl: ""
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-include-cache
- jekyll-seo-tag 
- jekyll-sitemap 

markdown: kramdown
kramdown:
input: GFM
hard_wrap: false

exclude: ["README.md", "Gemfile", "Gemfile.lock", "node_modules", "vendor"]


defaults:
- scope:
path: ""
type: "pages"
values:
layout: default


